# name: Delete Expired News

# on:
#   schedule:
#     - cron: '*/15 * * * *'
#   workflow_dispatch:

# jobs:
#   run-delete-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: npm install --no-audit --no-fund

#       - name: Run delete job
#         run: npm run job:delete
#         env:
#           TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
#           TARGET_CHAT_ID: ${{ secrets.TARGET_CHAT_ID }}
#           SOURCE_CHANNEL_USERNAME: ${{ secrets.SOURCE_CHANNEL_USERNAME }}
#           REQUEST_TIMEOUT_MS: ${{ secrets.REQUEST_TIMEOUT_MS }}
#           FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

